name: 'Localazy Upload'
description: 'Upload translations to Localazy, publish and promote tags.'
author: 'MegaverseBE'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  workdir: 
    description: 'Defines the working directory where to invoke Localazy CLI command.'
    required: false
    default: ''
  config_file: 
    description: 'The filename of the configuration file. Default: localazy.json'
    required: false
    default: 'localazy.json'
  read_key: 
    description: 'The read key for the project on Localazy.'
    required: false
    default: ''
  write_key: 
    description: 'The write key for the project on Localazy.'
    required: false
    default: ''
  publish:
    description: 'JSON string containing a branch:tag map for tag publishing.'
    required: false
    default: ''
  promote:
    description: 'JSON string containing a branch:[from,to] map for tag promoting.'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
